import requests
import cv2

BASE_URL = "http://192.168.1.195:8000"
API_KEY = "a165d599-2cea-4519-8470-32148366d24e"
3
class CompreFaceRecognitionAPI:
    def __init__(self,api_key, base_url):
        self.api_key = api_key
        self.base_url = base_url
        self.req = requests.Session()

        self.req.headers.update({"x-api-key": self.api_key})

    def list_faces(self):
        path = "/api/v1/recognition/subjects/"

        url = f"{self.base_url}{path}"
        response = self.req.get(url)
        if response.status_code != 200:
            raise Exception(response.text)
        else:
            return response.json()["subjects"]

        return response.json()

    def read_image_file(self, image_file):
        return open(image_file, "rb")


    def add_image_for_subject(self, subject, image_file):
        path = "/api/v1/recognition/faces"
        self.subjects = subject
        params = {"subject": subject}

        data = self.read_image_file(image_file)
        files = {"file": data}

        url = f"{self.base_url}{path}"
        response = self.req.post(url, params=params, files=files)
        if response.status_code not in (200,201):
            raise Exception(response.text)
        else:
            return response.json()

    def delete_image_for_subject(self, subject, image_file):
        path = "/api/v1/recognition/faces"

        params = {"subject": subject}

        data = self.read_image_file(image_file)
        files = {"file": data}

        url = f"{self.base_url}{path}"
        response = self.req.delete(url, params=params, files=files)
        if response.status_code not in (200, 204):
            raise Exception(response.text)
        else:
            return response.json()



if __name__ == '__main__':
    compreface=CompreFaceRecognitionAPI(API_KEY, BASE_URL)
    print(compreface.list_faces())

   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/Abhijit Kumbhar1.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_2296.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_2355.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_2387.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_2522.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_3546.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_3612.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_4700.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_5898.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_5955.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_6064.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_6535.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_7209.jpeg"))
   # print(compreface.add_image_for_subject("Abhijit Kumbhar","C:/Users/Kabra/Desktop/employee/abhijit Kumbhar/Abhijit Kumbhar_0_7284.jpeg"))
#
   ## print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande_.jpeg"))
   # print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_431.jpeg"))
   # print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_1008.jpeg"))
   # print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_1122.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_2671.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_2777.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_3460.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_3685.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_4152.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_4675.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_4796.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_5198.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_5659.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_6268.jpeg"))
   # print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_7029.jpeg"))
   # print(compreface.add_image_for_subject("Aditya Karande","C:/Users/Kabra/Desktop/employee/Aditya Karande/Aditya Karande_0_7059.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri.png"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_259.jpeg"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_381.jpeg"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_910.jpeg"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_1341.jpeg"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_2123.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_2125.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_2135.jpeg"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_2932.jpeg"))
    #print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_3040.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_3890.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_4840.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_5048.jpeg"))
   # print(compreface.add_image_for_subject("Ajay Shrotri","C:/Users/Kabra/Desktop/employee/Ajay Shrotri/Ajay Shrotri_0_5201.jpeg"))
   ## print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale_.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_473.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_581.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_660.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_1638.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_2183.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_2206.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_3971.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_4011.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_4184.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_4787.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_5418.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_5488.jpeg"))
   # print(compreface.add_image_for_subject("Akshay Kale_","C:/Users/Kabra/Desktop/employee/Akshay Kale/Akshay Kale_0_6593.jpeg"))
   ## print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_581.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_669.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_1735.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_2482.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_2568.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_2589.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_2634.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_2788.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_3698.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_3968.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_4125.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_4367.jpeg"))
   # print(compreface.add_image_for_subject("Amol Yadav","C:/Users/Kabra/Desktop/employee/Amol Yadav/Amol Yadav_0_6805.jpeg"))
   ## print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar_.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_353.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_711.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_1367.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_2149.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_2932.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_3394.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_4635.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_4872.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_5022.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_5249.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_5354.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_5432.jpeg"))
   # print(compreface.add_image_for_subject("Ashwini Darekar_","C:/Users/Kabra/Desktop/employee/Ashwini Darekar/Ashwini Darekar_0_5701.jpeg"))
   ## print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_68.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_116.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_223.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_324.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_670.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_896.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_1628.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_2206.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_2527.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_2833.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_3130.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_3905.jpeg"))
   # print(compreface.add_image_for_subject("Dhairyasheel Shinde","C:/Users/Kabra/Desktop/employee/Dhairyasheel Shinde/Dhairyasheel Shinde_0_3966.jpeg"))
   ## print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_43.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_275.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_508.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_573.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_994.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_1442.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_1840.jpeg"))
   # print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_1908.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_3822.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_4133.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_4192.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_4227.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_4266.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_4419.jpeg"))
    #print(compreface.add_image_for_subject("Dheeraj Devalekar","C:/Users/Kabra/Desktop/employee/Dheeraj Devalekar/Dheeraj Devalekar_0_6954.jpeg"))
   # print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_124.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_580.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_753.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_1644.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_1857.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_2612.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_2939.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_3341.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_3985.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_4228.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_4803.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_5250.jpeg"))
    #print(compreface.add_image_for_subject("Harsh Darak","C:/Users/Kabra/Desktop/employee/Harsh Darak/Harsh Darak_0_5625.jpeg"))
   ## print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/Hitesh C.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_164.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_368.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_571.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_778.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_1876.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_2207.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_2213.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_2848.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_3135.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_4205.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_5259.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_5368.jpeg"))
    #print(compreface.add_image_for_subject("Hitesh C","C:/Users/Kabra/Desktop/employee/HItesh C/Hitesh C_0_5951.jpeg"))
   # print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_108.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_1017.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_1210.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_1591.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_1839.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_3226.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_3374.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_3663.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_3911.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_5054.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_5341.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_5464.jpeg"))
    #print(compreface.add_image_for_subject("Jafar Ali","C:/Users/Kabra/Desktop/employee/Jafar Ali/Jafar Ali_0_6238.jpeg"))
   ## print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee/Komal Borkar.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_61.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_135.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_1553.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_1837.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_2250.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_2801.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_3526.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_3805.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_3999.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_4054.jpeg"))
    #print(compreface.add_image_for_subject("Komal Borkar","C:/Users/Kabra/Desktop/employee\Komal Borkar/Komal Borkar_0_4056.jpeg"))
   # print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot_1.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_876.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_889.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_989.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_1541.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_1813.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_1991.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_2023.jpeg"))
   #print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_2298.jpeg"))
   # print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_2336.jpeg"))
   # print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_2385.jpeg"))
   # print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_2989.jpeg"))
   # print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_5321.jpeg"))
   # print(compreface.add_image_for_subject("Manjusha Dhoot_1","C:/Users/Kabra/Desktop/employee/Manjusha Dhoot/Manjusha Dhoot_0_5605.jpeg"))
   # print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_95.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_138.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_996.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_2419.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_3095.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_3280.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_6789.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_6024.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_5188.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_7391.jpeg"))
    #print(compreface.add_image_for_subject("Mayuri Gaikwad","C:/Users/Kabra/Desktop/employee/Mayuri Gaikwad/Mayuri Gaikwad_0_6854.jpeg"))
   # print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_376.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_799.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_1853.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_2128.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_2380.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_3304.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_3946.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_8463.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_9188.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_6224.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_5684.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_9385.jpeg"))
    #print(compreface.add_image_for_subject("Mohini Pote","C:/Users/Kabra/Desktop/employee/Mohini Pote/Mohini Pote_0_9478.jpeg"))
   # print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/Nilesh Gore_1.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_495.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_1995.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_2078.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_3345.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_3659.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_4482.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_3672.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_4556.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_4629.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_6133.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_7321.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_8469.jpeg"))
    #print(compreface.add_image_for_subject("Nilesh Gore_1","C:/Users/Kabra/Desktop/employee/NIlesh Gore/Nilesh Gore_0_9578.jpeg"))
   # print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_276.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_1519.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_2141.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_3164.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_4563.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_4900.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_6717.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_6707.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_7318.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_7316.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_7246.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_7318.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Anekar","C:/Users/Kabra/Desktop/employee/Pratik Anekar/Pratik Anekar_0_8685.jpeg"))
   # print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_491.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_510.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_933.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_3087.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_1711.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_3314.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/zemployee/Ruchita Sinkar/Ruchita Sinkar_0_4706.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_4861.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_5392.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_6853.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_9249.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_9861.jpeg"))
    #print(compreface.add_image_for_subject("Ruchita Sinkar","C:/Users/Kabra/Desktop/employee/Ruchita Sinkar/Ruchita Sinkar_0_6853.jpeg"))
   # print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_725.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_786.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_1179.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_3682.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_5881.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_7687.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_8260.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_8774.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_7670.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_9095.jpeg"))
    #print(compreface.add_image_for_subject("Siddhart Parale","C:/Users/Kabra/Desktop/employee/Siddhart Parale/Siddhart Parale_0_9458.jpeg"))
   ## print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure_.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_920.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_1499.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_2078.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_2288.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_2818.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_3897.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_3997.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_5099.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_6518.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_8826.jpeg"))
    #print(compreface.add_image_for_subject("Sumit Tanpure_","C:/Users/Kabra/Desktop/employee/Sumit Tanpure/Sumit Tanpure_0_9750.jpeg"))
   # print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak_1.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_1768.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_1773.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_2776.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_3236.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_4663.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_5841.jpeg"))
    #print(compreface.add_image_for_subject("Suraj Chalak_1","C:/Users/Kabra/Desktop/employee/Suraj Chalak/Suraj Chalak_0_4518.jpeg"))
   # print(compreface.add_image_for_subject("Sohum Kabra","D:\sohum\sohum.jpg"))
    #print(compreface.add_image_for_subject("Pankaj Zanwar","C:/Users/Kabra/Desktop/employee/pankaj sir.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar.jpg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_223.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_246.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_463.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_509.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_941.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_1088.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_2254.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_2549.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_2618.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_2880.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_3370.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_4140.jpeg"))
    #print(compreface.add_image_for_subject("Nihar Zanwar","C:/Users/Kabra/Desktop/employee/Nihar Zanwar/Nihar Zanwar_0_6765.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni.jpg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_101.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_824.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_1014.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_2053.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_3098.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_5611.jpeg"))
    #print(compreface.add_image_for_subject("Pratik Kulkarni","C:/Users/Kabra/Desktop/employee/Pratik Kulkarni/Pratik Kulkarni_0_8775.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar.jpg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_278.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_446.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_1735.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_3293.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_5775.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_6388.jpeg"))
    #print(compreface.add_image_for_subject("Aditya Inamdar","C:/Users/Kabra/Desktop/employee/Aditya Inamdar/Aditya Inamdar_0_9245.jpeg"))





else:
    print("1")


